### PR TITLE
change liteserver storage to tonapi client to get jetton info in the …

### PR DESCRIPTION
**Pull request by zakhar-petukhov**
…rates method

### CODE REVIEW

**Comment by thedemons** [comment]
Hey, could you explain the reasoning behind this change?

**Comment by mr-tron** [comment]
good question

**Comment by thedemons** [comment]
I'm getting a lot of errors because tonapi.io API is rate-limited, the whole point of running opentonapi is to use my own node & lite server, I don't understand why this change is necessary.

```
2024-04-08 13:00:36 {"time":"2024-04-08T06:00:36.334764054Z","level":"ERROR","prefix":"-","file":"market.go","line":"122","message":"[sendRequest] bad status code: 429, https://tonapi.io/v2/jettons/0:54bf44ac61bfc7a535fe5dd3a0149c1b99dda284c7115e75b52a99819850beb6"}
2024-04-08 13:00:36 {"time":"2024-04-08T06:00:36.334789996Z","level":"ERROR","prefix":"-","file":"market.go","line":"480","message":"[convertedDedustPoolResponse] failed to get jetton info: bad status code: 429"}
```

**Comment by bobbychen** [comment]
@thedemons  Did you solved this problem?

**Comment by thedemons** [comment]
> @thedemons Did you solved this problem?

Yes, I just did it the easy way and change the url back to localhost, also keep in mind that when you run the docker using the provided command in READMD.md, it will use an image on docker hub instead of using your source. So you should build your own image instead.

**Comment by ImTheDeveloper** [comment]
Trying to build using my own file local just throws a bunch of new errors. These commits are brutal.

**Pull request merged**
